### ISSUE TITLE
Robot library

### ISSUE THREAD

**Issue by Aloto10107** [Axolotl10107/FtcRobotController#1]
Create a library which represents the robot and contains all of its physical components as software objects.
For example, to access the left motor:
robot.leftFront
It can also be used for larger general functions:
robot.drive(forwardComponent, rightComponent);

**Comment by MediumAutomaton** [comment]
An example implementation of this now exists. It is utilized in the "PowerNap" OpMode in the "meddev" (Michael's) branch.
